name: "ometa_demo"
version: "1.0.0"
config-version: 2

profile: "ometa_demo"

model-paths: ["models"]

models:
  dera_dbt:
    +materialized: view
    staging:
      +schema: stg
    intermediate: 
      + schema
