version: 2

models:
  - name: financials
    description: "Consolidated financial metrics for each registrant and fiscal year. Combines revenue, income, market float, debt, cash, and assets into a single view. Sources data from t_r (revenue), t_i (income), t_f (float), t_d (debt),  t_c (cash), and t_a (assets)."
    config:
      meta:
        openmetadata:
          displayName: "Financials Consolidated"
          glossary: []
    columns:
      - name: name
        description: "Registrant name as recorded in EDGAR."
        meta:
          openmetadata:
            displayName: "Registrant Name"
            glossary: ['identifiers.name']

      - name: cik
        description: "Central Index Key (CIK) assigned by the SEC to each registrant."
        meta:
          openmetadata:
            displayName: "Central Index Key (CIK)"
            glossary: ['identifiers.cik']

      - name: fy
        description: "Fiscal year of the filing."
        meta:
          openmetadata:
            displayName: "Fiscal Year"
            glossary: []

      - name: ddate
        description: "End date for the reported or consolidated metrics."
        meta:
          openmetadata:
            displayName: "Data Date"
            glossary: []

      - name: sic
        description: "Standard Industrial Classification code of the registrant."
        meta:
          openmetadata:
            displayName: "SIC Code"
            glossary: ['identifiers.sic', 'financial_kpis.relative_debt_ratio', 'financial_kpis.relative_profit_margin', 'financial_kpis.relative_return_on_assets_roa', 'financial_kpis.liquidity_index']

      - name: revenue_usd
        description: "Annual revenue expressed in USD."
        meta:
          openmetadata:
            displayName: "Revenue (USD)"
            glossary: ['financial_kpis.market_cap_to_revenue', 'financial_kpis.profit_margin', 'financial_kpis.asset_turnover_ratio', 'financial_kpis.revenue_to_assets_ratio', 'financial_kpis.debt_to_revenue_ratio', 'esg_financial_kpis.revenue_per_climate_risk']

      - name: income_usd
        description: "Annual income expressed in USD."
        meta:
          openmetadata:
            displayName: "Income (USD)"
            glossary: ['financial_kpis.profit_margin', 'financial_kpis.return_on_assets_roa', 'financial_kpis.income_to_market_cap_ratio']

      - name: market_cap_usd
        description: "Market float value expressed in USD."
        meta:
          openmetadata:
            displayName: "Market Float (USD)"
            glossary: ['financial_kpis.market_cap_to_revenue', 'financial_kpis.income_to_market_cap_ratio', 'esg_financial_kpis.market_cap_per_esg_opportunity']

      - name: debt_usd
        description: "Total debt expressed in USD."
        meta:
          openmetadata:
            displayName: "Debt (USD)"
            glossary: ['financial_kpis.cash_ratio', 'financial_kpis.debt_to_assets_ratio', 'financial_kpis.debt_to_revenue_ratio']

      - name: cash_usd
        description: "Cash and cash equivalents expressed in USD."
        meta:
          openmetadata:
            displayName: "Cash (USD)"
            glossary: ['financial_kpis.cash_ratio', 'financial_kpis.cash_to_assets_ratio', 'esg_financial_kpis.cash_resilience_to_physical_risk']

      - name: assets_usd
        description: "Total assets expressed in USD."
        meta:
          openmetadata:
            displayName: "Assets (USD)"
            glossary: ['financial_kpis.debt_to_assets_ratio', 'financial_kpis.return_on_assets_roa', 'financial_kpis.asset_turnover_ratio', 'financial_kpis.cash_to_assets_ratio', 'financial_kpis.revenue_to_assets_ratio']

  - name: float
    description: "Provides the latest available public float value for each company based on LEI. Selects the most recent float value from int_float_inferred and stg_dera_sub."
    config:
      meta:
        openmetadata:
          displayName: "Latest Float Value"
          glossary: []
    columns:
      - name: lei
        description: "Legal Entity Identifier (LEI) of the registrant."
        config:
          meta:
            openmetadata:
              displayName: "Legal Entity Identifier (LEI)"
              glossary: []

      - name: company_name
        description: "Name of the company as recorded in EDGAR."
        config:
          meta:
            openmetadata:
              displayName: "Company Name"
              glossary: []

      - name: latest_float_value_usd
        description: "Most recent public float value expressed in USD."
        config:
          meta:
            openmetadata:
              displayName: "Latest Float Value (USD)"
              glossary: []

      - name: last_ddate
        description: "Date associated with the latest float value."
        config:
          meta:
            openmetadata:
              displayName: "Last Data Date"
              glossary: []
