CREATE USER dbt WITH PASSWORD 'dbt';

GRANT CONNECT ON DATABASE dera TO dbt;
GRANT CREATE ON DATABASE dera TO dbt;

CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION dbt;

GRANT USAGE, CREATE ON SCHEMA raw TO dbt;
GRANT USAGE, CREATE ON SCHEMA public TO dbt;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dbt;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dbt;